name: Daily Market Update

on:
  schedule:
    # 1:00 PM Nigeria time (WAT)
    # GitHub Actions uses UTC
    - cron: "0 8 * * 1-5"

  workflow_dispatch:

jobs:
  market-update:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Send Daily Market Update
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TWELVE_DATA_API_KEY: ${{ secrets.TWELVE_DATA_API_KEY }}
        run: |
          python marketupdate.py
